name: Local Development Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  terraform-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.5
        terraform_wrapper: false

    - name: Terraform Format
      id: fmt
      run: |
        cd terraform
        terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: |
        cd terraform
        terraform init

    - name: Terraform Validate
      id: validate
      run: |
        cd terraform
        terraform validate -no-color

  ansible-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Ansible
      run: |
        pip install ansible

    - name: Run Ansible Playbook in check mode
      run: |
        ansible-playbook -i ansible/inventory/local ansible/playbooks/local_setup.yml --check -v